export const SETBGCOL = "SETBGCOL";
export const SETEXAMPLECOL = "SETEXAMPLECOL";
export const ADDBOXSHADOW = "ADDBOXSHADOW";
export const REMOVEBOXSHADOW = "REMOVEBOXHADOW";
export const CHANGEACTIVEID = "CHANGEACTIVEID";

export const SETOFFSETX = "SETOFFSETX";
export const SETOFFSETY = "SETOFFSETY";
export const SETSPREAD = "SETSPREAD";
export const SETBLUR = "SETBLUR";
