export const SETBGCOL = "SETBGCOL";
export const SETEXAMPLECOL = "SETEXAMPLECOL";
export const SETEXAMPLERADIUS = "SETEXAMPLERADIUS";
export const ADDBOXSHADOW = "ADDBOXSHADOW";
export const REMOVEBOXSHADOW = "REMOVEBOXHADOW";
export const CHANGEACTIVEID = "CHANGEACTIVEID";

export const SETOFFSETX = "SETOFFSETX";
export const SETOFFSETY = "SETOFFSETY";
export const SETSPREAD = "SETSPREAD";
export const SETBLUR = "SETBLUR";
export const SETINSET = "SETINSET";
export const SETSHADOWCOLOR = "SETSHADOWCOLOR";
export const SETLIST = "SETLIST";
